[build]
  command = "npm i --no-save lightningcss-linux-x64-gnu && npx prisma generate && npx prisma db push --accept-data-loss && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
