"use client";
import { FormEvent, useEffect, useState } from "react";

type User = { id:string; email:string; role:"ADMIN"|"VIEWER"; active:boolean; lastLoginAt:string|null; createdAt:string };
export default function UsersPage() {
  const [users,setUsers]=useState<User[]>([]); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [role,setRole]=useState<"ADMIN"|"VIEWER">("VIEWER"); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function load(){ const r=await fetch("/api/admin/users"); const d=await r.json(); if(r.ok)setUsers(d.data||[]); else setError(d.error?.message||"Unable to load users"); }
  useEffect(()=>{load()},[]);
  async function create(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,role})});const d=await r.json();if(!r.ok){setError(d.error?.message||"Unable to create user");return;}setEmail("");setPassword("");setMessage("User created successfully.");load();}
  async function change(id:string, patch:Partial<User>&{password?:string}){setError("");const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...patch})});const d=await r.json();if(!r.ok){setError(d.error?.message||"Update failed");return;}load();}
  async function remove(id:string){if(!confirm("Delete this account permanently?"))return;const r=await fetch("/api/admin/users?id="+encodeURIComponent(id),{method:"DELETE"});const d=await r.json();if(!r.ok)setError(d.error?.message||"Delete failed");else load();}
  return <div className="space-y-8"><div><h2 className="text-2xl font-bold">User Access</h2><p className="text-zinc-400 text-sm">Admins can create, disable, delete, reset passwords, and change roles.</p></div><form onSubmit={create} className="grid md:grid-cols-4 gap-3 bg-zinc-900/60 border border-zinc-800 rounded-2xl p-5"><input required type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} className="bg-zinc-950 border border-zinc-700 rounded-lg p-3"/><input required minLength={12} type="password" placeholder="Temporary password" value={password} onChange={e=>setPassword(e.target.value)} className="bg-zinc-950 border border-zinc-700 rounded-lg p-3"/><select value={role} onChange={e=>setRole(e.target.value as any)} className="bg-zinc-950 border border-zinc-700 rounded-lg p-3"><option value="VIEWER">Viewer</option><option value="ADMIN">Admin</option></select><button className="rounded-lg bg-emerald-500 text-zinc-950 font-semibold p-3">Create account</button></form>{message&&<div className="text-emerald-400 text-sm">{message}</div>}{error&&<div className="text-rose-400 text-sm">{error}</div>}<div className="overflow-x-auto bg-zinc-900/60 border border-zinc-800 rounded-2xl"><table className="w-full text-sm"><thead className="text-zinc-400 border-b border-zinc-800"><tr><th className="text-left p-4">Email</th><th className="text-left p-4">Role</th><th className="text-left p-4">Status</th><th className="text-left p-4">Last login</th><th className="text-left p-4">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-zinc-800/60"><td className="p-4">{u.email}</td><td className="p-4"><select disabled={u.id===undefined} value={u.role} onChange={e=>change(u.id,{role:e.target.value as any})} className="bg-zinc-950 border border-zinc-700 rounded px-2 py-1"><option>VIEWER</option><option>ADMIN</option></select></td><td className="p-4">{u.active?"Active":"Disabled"}</td><td className="p-4 text-zinc-500">{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():"Never"}</td><td className="p-4 flex gap-2"><button onClick={()=>change(u.id,{active:!u.active})} className="px-3 py-1 rounded bg-zinc-800">{u.active?"Disable":"Enable"}</button><button onClick={()=>{const p=prompt("Enter a new password (minimum 12 characters):");if(p)change(u.id,{password:p})}} className="px-3 py-1 rounded bg-zinc-800">Reset password</button><button onClick={()=>remove(u.id)} className="px-3 py-1 rounded bg-rose-950 text-rose-300">Delete</button></td></tr>)}</tbody></table></div></div>;
}
